### ISSUE TITLE
Mongoid 3.0: undefined method `database' for Mongoid:Module (NoMethodError)

### ISSUE THREAD

**Issue by ADogan** [DatabaseCleaner/database_cleaner#113]
In database_cleaner 0.7.2, I get the following error after upgrading Mongoid to 3.0:

<pre>
undefined method `database' for Mongoid:Module (NoMethodError)

..
/gems/database_cleaner-0.7.2/lib/database_cleaner/mongoid/truncation.rb:15:in `database'
/gems/database_cleaner-0.7.2/lib/database_cleaner/mongo/truncation.rb:17:in `collections'
/gems/database_cleaner-0.7.2/lib/database_cleaner/mongo/truncation.rb:9:in `clean'
/gems/database_cleaner-0.7.2/lib/database_cleaner/base.rb:77:in `clean'
/gems/database_cleaner-0.7.2/lib/database_cleaner/configuration.rb:56:in `block in clean'
/gems/database_cleaner-0.7.2/lib/database_cleaner/configuration.rb:56:in `each'
/gems/database_cleaner-0.7.2/lib/database_cleaner/configuration.rb:56:in `clean'
/gems/cucumber-rails-1.3.0/lib/cucumber/rails/hooks/database_cleaner.rb:9:in `After'

</pre>
